<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ReadThreadTest extends TestCase
{
    use DatabaseMigrations;
    protected $thread;
    /**
     * A basic test example.
     * @test
     * @return void
     */

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }
    /**
     * A basic test example.
     * @test
     * @return void
     */
    public function a_user_can_browse_threads()
    {

        $response = $this->get('/threads')
            ->assertSee($this->thread->title);
    }
    /**
     * A basic test example.
     * @test
     * @return void
     */
    public function a_user_can_view_single_thread(){
        $response = $this->get($this->thread->path())
            ->assertSee($this->thread->title);
    }
    /**
     * A basic test example.
     * @test
     * @return void
     */
    public function a_user_can_read_replies_that_are_associated_with_a_thread(){
        //given a thread with a replies
        // then we see the thread and replies
        $reply= factory('App\Reply')->create(['thread_id'=>$this->thread->id]);
        $response = $this->get($this->thread->path())
            ->assertSee($reply->body);
    }
}
